// Generated by CoffeeScript 2.0.0-beta7
void function () {
  var _, candiateWords, path, removePunctuation, stopWords, stopwords;
  path = require('path');
  stopWords = require('../data/stopwords/stopwords-en.json');
  _ = require('lodash');
  module.exports = stopwords = function (content, language) {
    var count, overlappingStopwords, strippedInput, words;
    if (null == language)
      language = 'en';
    if (language !== 'en')
      console.error("WARNING: No stopwords file found for '" + language + "' - defaulting to English!");
    strippedInput = removePunctuation(content);
    words = candiateWords(strippedInput);
    overlappingStopwords = [];
    count = 0;
    _.each(words, function (w) {
      count += 1;
      if (stopWords.indexOf(w.toLowerCase()) > -1)
        return overlappingStopwords.push(w.toLowerCase());
    });
    return {
      wordCount: count,
      stopwordCount: overlappingStopwords.length,
      stopWords: overlappingStopwords
    };
  };
  removePunctuation = function (content) {
    return content.replace(/[\|\@\<\>\[\]\"\'\.,-\/#\?!$%\^&\*\+;:{}=\-_`~()]/g, '');
  };
  candiateWords = function (strippedInput) {
    return strippedInput.split(' ');
  };
}.call(this);
